# Importar y cargar datos

In [10]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import QuantileTransformer

df = pd.read_csv("./data/titanic_clean.csv")

df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

# Codificación de variables categóricas

In [11]:
label_encoder = LabelEncoder()

df["Sex"] = label_encoder.fit_transform(df["Sex"])

df["Embarked"] = label_encoder.fit_transform(df["Embarked"])

df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

# Separar variables predictoras y objetivo

In [12]:
X = df.drop("Survived", axis=1)

y = df["Survived"]

print("Variables predictoras:")
display(X.head())

print("Variable objetivo:")
display(y.head())

Variables predictoras:

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  22.0      1      0   7.2500         2
1       1    0  38.0      1      0  71.2833         0
2       3    0  26.0      0      0   7.9250         2
3       1    0  35.0      1      0  53.1000         2
4       3    1  35.0      0      0   8.0500         2

Variable objetivo:

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

# Guardar dataset procesado

In [13]:
processed_df = pd.concat([X, y], axis=1)

processed_df.to_csv("./data/titanic_feature_engineering.csv", index=False)

print("Dataset procesado guardado correctamente.")

Dataset procesado guardado correctamente.

## Conclusión

Se realizó el proceso de feature engineering transformando variables categóricas a valores numéricos y separando las variables predictoras de la variable objetivo. Esto deja el dataset listo para entrenar modelos de machine learning.